name: bitsumb2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  web_socket_channel: ^2.1.0
  uuid : ^3.0.6
  nonce: ^1.2.0
  intl:
  animated_text_kit: ^4.2.1
  dart_eval : 0.2.0
  candlesticks_plus: ^1.0.7
  http:
  webview_flutter: ^3.0.2
  radio_group_v2: ^1.0.2
  shimmer: ^2.0.0
  fl_chart: ^0.50.1
  crypto_font_icons: ^1.0.1
  sizer: ^2.0.15
  google_fonts: ^2.3.1
  unicons: ^2.1.0
  k_chart: ^0.6.1

  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

